### ISSUE TITLE
numpy-1.10 compatibility

### ISSUE THREAD

**Issue by bgoli** [PySCeS/pysces#15]
Hi

Jannie reported an issue with PyscesStoich and the new numpy 1.10 series. This occurs as a result of a change to numpy.concatenate. Essentially: scipy.concatenate((a,b,...), 1) now generates an error and should be replaced with with scipy.hstack((a,b, ...)).

I've created a branch numpy-1.10 that fixes the problem, if you could test it out with some (non-test) models on your current setups and let me know if it works I'll merge it into the main branch.

Cheers
b.

**Comment by jmrohwer** [comment]
Works fine now, tested on a number of models, also larger models (Rohwer-sucrose). I have merged into master and pushed.

**Comment by bgoli** [comment]
Thanks!
