### ISSUE TITLE
If and else clause have same code PyscesSED.py

### ISSUE THREAD

**Issue by matthiaskoenig** [PySCeS/pysces#18]
Hi Bret,
just looked over the PyscesSED.py file and the following does not make sense.
The best M

```
    def addModel(self, id, model):
        try:
            if not self.models.has_key(id):
                self.models[id] = model.clone()
            else:
                self.models[id] = model.clone()
```

**Comment by bgoli** [comment]
Thanks will look into it, I mostly work with a single model so missed this one.

**Comment by matthiaskoenig** [comment]
Not really using it, just read over the code and caught my attention.
M

**Comment by bgoli** [comment]
fixed.
