### ISSUE TITLE
simulations with libRoadRunner

### ISSUE THREAD

**Issue by bgoli** [PySCeS/pysces#20]
Herbert's libRoadrunner looks to pretty much have everything we need for a time-course/integration component, handles events, rules and other SBML stuff. I've had a look at it and the only "issue" is that it takes an SBML file as input. While this will not be optimal for performance (not so important for complex simulations anyway) I could imagine the following (pseudocode):

`def ROADRUNNER()
  fast conversion of current model state to minimal valid SBML required for libRoadrunner
  instantiate roadrunner object from SBML file on first call to ROADRUNNER or use existing if run > 1
  initialise new or exisitng roadrunner object to current model state
  initialise solver 
  run simulation
  map results back to PySCeS model object
 `
what do you think, this would solve the PySUNDIALS dependency, event handling (including L3) and and is based on CVODE which is arguably the best algorithm out there.

Anyone interested, what do you think?

**Comment by jmrohwer** [comment]
To a certain extent this is superseded by the use of [assimulo](../../pysces/tree/assimulo) for CVODE, event handling is possible again. While `ROADRUNNER()` might be a nice idea I'm not sure it's worth the effort. And there have been no takers for more than 4 years, I'm closing the issue.
