### ISSUE TITLE
PySCeS on OSX High Sierra: nleq2 error

### ISSUE THREAD

**Issue by bgoli** [PySCeS/pysces#30]
Hi
A student installed the Anaconda PySCeS package for OSX High Sierra 10.13.6 and is getting the following nleq2 error:

![image](https://user-images.githubusercontent.com/5011985/45102078-22c85880-b12d-11e8-81c6-fa7678bb47cc.png)

Has anyone with a Mac run into this problem before?

**Comment by jmrohwer** [comment]
I can't reproduce this on OSX 10.13.3 in a fresh conda env, pysces installed with
> conda install -c bgoli -c sbmlteam pysces

Everything seems to work and the `nleq2` object does exist:
```python
In [9]: m = pysces.model('pysces_test_branch1')
Assuming extension is .psc
Using model directory: /Users/jr/Pysces/psc
/Users/jr/Pysces/psc/pysces_test_branch1.psc loading ..... 
Parsing file: /Users/jr/Pysces/psc/pysces_test_branch1.psc
 
Calculating L matrix . . . . . . .  done.
Calculating K matrix . . . . . . .  done.
 

In [10]: m.mode_solver='NLEQ2'

In [11]: m.State()
(nleq2) The solution converged.

In [12]: m.showState()

Steady-state species concentrations
s1_ss = 4.8584e+00
s2_ss = 1.8855e+00
s3_ss = 1.4912e+00
s4_ss = 1.4912e+00

Steady-state fluxes
J_R0 = 2.4214e+00
J_R1 = 2.4214e+00
J_R2 = 1.2107e+00
J_R3 = 1.2107e+00
J_R4 = 1.2107e+00
J_R5 = 1.2107e+00

In [13]: pysces.nleq2.nleq2
Out[13]: <fortran object>

In [14]: id(pysces.nleq2.nleq2)
Out[14]: 4758184104
```
Only difference I can see is that above is anaconda3 (albeit with a python2.7 environment) whereas I have anaconda 2. Dunno whether it makes a difference. Should be okay for python itself, but I'm not sure about the fortran extension modules.

**Comment by bgoli** [comment]
Thanks, I will look into this in more detail.

**Comment by jmrohwer** [comment]
Should work with latest conda builds on macOS. Alternatively pip install it from PyPI. The binary wheels have been processed with [delocate](https://github.com/matthew-brett/delocate) to package the dynamically linked library dependencies with the wheel so the linker can find them.
