### ISSUE TITLE
writeMod2SBML doesn't work in python 3.7

### ISSUE THREAD

**Issue by ortega2247** [PySCeS/pysces#34]
Hi, I just started using pysces and was trying to export a model to sbml. I used the example provided by the documentation in a conda environment with python 3.7: 
`mod = pysces.model('pysces_test_linear1')`
`pysces.interface.writeMod2SBML(mod, 'bla.xml')`

and got this error:
AssertionError: 
Problems loading SBML/Python interface

Interestingly, the export function works in python 3.6 

Thanks for you help

**Comment by bgoli** [comment]
fixed in latest release
