### ISSUE TITLE
Simulation sometimes results differ from other tools

### ISSUE THREAD

**Issue by jonrkarr** [PySCeS/pysces#44]
This was noticed by @freiburgermsu.

### Example model (Elowitz repressilator model)
- [SBML](https://github.com/biosimulators/Biosimulators_test_suite/tree/dev/examples/sbml-core/Elowitz-Nature-2000-Repressilator)
- [CellML](https://github.com/biosimulators/Biosimulators_test_suite/tree/dev/examples/cellml/Elowitz-Nature-2000-Repressilator)

#### PySCeS
PySCeS' results are internally consistent between CVODE and LSODA, but different from that of other tools that also use LSODA and CVODE

![PySCeS](https://user-images.githubusercontent.com/2848297/128947407-6338b66e-ed2c-46bc-88de-d8f7a7ec44be.JPG)

#### COPASI (LSODA)
![COPASI](https://user-images.githubusercontent.com/2848297/128947408-a56c2044-04d4-4c2c-9dae-b19415f01e91.JPG)

#### OpenCOR (CVODE)
![OpenCOR (CellML)](https://user-images.githubusercontent.com/2848297/128947409-31b354eb-bfe3-4b0b-9d02-8e6e9f3b3cf8.JPG)

### Interactive versions of the same results
- [SBML/PySCeS/CVODE](https://run.biosimulations.org/simulations/6111b2f3685c692d81b41160)
- [SBML/COPASI/LSODA](https://run.biosimulations.org/simulations/6111b34f685c691302b4116f)
- [CellML/OpenCOR/CVODE](https://run.biosimulations.org/simulations/6111bd56685c693ca5b41178)

**Comment by bgoli** [comment]
@jonrkarr thanks for the report, I will look into it.

**Comment by jmrohwer** [comment]
[BIOMD0000000012_url.xml.psc.txt](https://github.com/PySCeS/pysces/files/6967653/BIOMD0000000012_url.xml.psc.txt)

The bug is in the SBML parser. The `<ln/>` MathML operator is translated to `math.log10` in the PSC file. Corrected PSC file attached above. This gives the correct results. @bgoli  you wrote the SBML conversion code, would you be able to pinpoint this quickly?

**Comment by jonrkarr** [comment]
Maybe Frank Bergmann could shed light on how COPASI does it. 

Thanks for the explanation. GillesPy2 has similar issue with this model. I only realized this from your explanation about ln. In their case, they raise an exception which indicates they don't know how to interpret ln.

**Comment by bgoli** [comment]
@jmrohwer thanks for finding the problem this, I will look into this in more detail. We probably notice the problem as we use the L2 infix translator while COPASI would use the ASTnodes directly.

**Comment by jmrohwer** [comment]
This #45 fixes it, but I am not sure if you would want to make more significant changes in terms of using the AST nodes vs infix translator. Also, SBML export from the PSC file does not work 100% (assignment rules are not properly translated), this most probably has to do with PySCeS still using SBML L2 internally.

**Comment by jmrohwer** [comment]
Fixed in #53
