### ISSUE TITLE
PySCeS website

### ISSUE THREAD

**Issue by bgoli** [PySCeS/pysces#49]
I will update https://pysces.github.io/ for this release and redirect the pysces.sourceforge.net to it.

**Comment by jmrohwer** [comment]
:+1:

**Comment by bgoli** [comment]
Prototype new website now mirrored on both https://pysces.github.io/ and https://pyscces.sourceforge.net I will add/transfer more information over time, but this is a good enough start for now (the old site can still be found in the legacy/ folder).

**Comment by bgoli** [comment]
I will update the website with the new information once we have done the release.

**Comment by bgoli** [comment]
@bgoli websites need updating to 1.0.2
