### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by jmrohwer** [PySCeS/pysces#54]
As per https://github.com/github/renaming, if you are happy I will go ahead. Bring nomenclature into the 21st century :smile:

**Comment by bgoli** [comment]
I've done this with my other projects, the thing is you need to reconfigure all your local copies ... after the release would be good.

**Comment by jmrohwer** [comment]
@bgoli `master` has been renamed to `main` now that release `1.0.0` is out. You will have to update your local copy. I have also created a new branch `development` (currently even with main) for further development as per https://github.com/PySCeS/pysces/wiki/PySCeS-releases
