### ISSUE TITLE
update PLY and check other support libraries

### ISSUE THREAD

**Issue by bgoli** [PySCeS/pysces#55]
Reminder that I should update PLY in lib and core2

**Comment by bgoli** [comment]
Turns out we are using the last legacy release 3.11 and eagerly await PLY 4.0 (https://github.com/dabeaz/ply)

**Comment by jmrohwer** [comment]
Incidentally, why don't we include this as a dependency, why are you manually copying the files? (Was wondering about that previously).

**Comment by bgoli** [comment]
There are issues with imports and I like having a static version that works. Also in general would rather reduce module dependencies.

**Comment by jmrohwer** [comment]
That's a good point, only thing is you then manually have to keep checking for updates. But if the static version works for your purposes then that's good enough I guess.

**Comment by bgoli** [comment]
PLY is stable and rarely updated so I only need to check every few years
