### ISSUE TITLE
PySCeS cannot import some converted models

### ISSUE THREAD

**Issue by jonrkarr** [PySCeS/pysces#59]
For example, importing [BIOMD0000000297_url.xml.txt](https://github.com/PySCeS/pysces/files/7010010/BIOMD0000000297_url.xml.txt) (SBML L2V4)

```python
import pysces
import tempfile
interfaces = pysces.PyscesInterfaces.Core2interfaces()
fid, model_filename = tempfile.mkstemp(suffix='.psc')
interfaces.convertSBML2PSC('BIOMD0000000297_url.xml', pscfile=model_filename)
model = pysces.model(model_filename)
```

results in this error
```
AssertionError: 
Lexer Failure:
['|', '|']
```

Environment
* PySCeS: 470cd0b8afa4c14721a2b2bc00d4c71d80603801
* Python: 3.9.6
* OS: Ubuntu

**Comment by bgoli** [comment]
Thanks for the report.
