### ISSUE TITLE
GitHub tags don't match PyPI versions

### ISSUE THREAD

**Issue by yurivict** [PySCeS/pysces#69]
Last tag is ```0.9.8a``` and current PyPI version is ```0.9.8.post2```.
```0.9.8.post2``` isn't in tags.

**Comment by jmrohwer** [comment]
Yes, we are aware of this, it was an oversight on our part. We plan to release `1.0.0` in the coming days by which time everything should be in sync again.

**Comment by jmrohwer** [comment]
Version `1.0.0` has just been released and the Github tag and PyPI version are in sync again.
