### ISSUE TITLE
Source tarball isn't on PyPI

### ISSUE THREAD

**Issue by yurivict** [PySCeS/pysces#70]
https://pypi.org/project/pysces/#files

**Comment by jmrohwer** [comment]
Yes, we are aware of this, it was an oversight on our part. We plan to release `1.0.0` in the coming days by which time everything should be in sync again, including source tarballs.

**Comment by jmrohwer** [comment]
Version `1.0.0` has just been released and the packages (including source tarball) are on PyPI.
