### ISSUE TITLE
ToDo before 1.0.0 release

### ISSUE THREAD

**Issue by jmrohwer** [PySCeS/pysces#71]
I've started preparing a checklist of what needs to be done before the 1.0.0 release so that we don't forget about anything. Feel free to add. I've assigned some of the jobs, feel free to change/edit.

- ~~update docs submodule with the most recent link and check that RTD build works - @jmrohwer~~ 
- ~~manually build a PDF of the user guide and upload to source - @jmrohwer~~
- ~~check building of wheels and anaconda packages by manually triggering workflows (they will not be uploaded to Anaconda.org/PyPI) - @jmrohwer~~
- ~~finalize release notes - @jmrohwer / @bgoli~~
- ~~tag version 1.0.0 and craft GitHub release - @jmrohwer (I don't mind doing this but don't have to)~~
- ~~prepare zenodo release - @bgoli (would appreciate if you do this as you have done it before and sorted things out)~~ [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5532838.svg)](https://doi.org/10.5281/zenodo.5532838)
- ~~add badges for RTD and the GitHub CI actions to the main README.md - @jmrohwer~~

**Comment by bgoli** [comment]
All looks good to me

**Comment by bgoli** [comment]
@jmrohwer I've merged in my changes. With respect to tagging, I think when you make a release the repository is automatically tagged with the release version, so you don't need to manually create a release tag.

**Comment by jmrohwer** [comment]
@bgoli Did you get my comments on your latest merge? A couple of minor issues, let me know if you are happy with that. I have not changed the code (yet) but am happy to do so if you are too busy.

Still had some issues to sort out with the CI build, hopefully all is good now. Anaconda build on Python 3.6 gives version conflicts using the Anaconda compilers on macOS. I guess it has to do with available numpy versions. I dropped 3.6, figured if people are using Anaconda, it is trivial to upgrade to a more recent version. Python 3.7-3.9 seem to build okay.

**Comment by jmrohwer** [comment]
@bgoli Release version `1.0.0` is out. :grin: 
Wheels and source tarball are on PyPI. Anaconda packages are building at the moment.
Go ahead and prepare the zenodo release!

**Comment by bgoli** [comment]
Great 👍 Unfortunately, something went wrong and the release failed to get to Zenodo I may have to do it all manually which will take some time.

**Comment by bgoli** [comment]
Zenodo record created [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5532838.svg)](https://doi.org/10.5281/zenodo.5532838) I'll update the readme and website and CFF file with the final release info.

**Comment by jmrohwer** [comment]
Great :+1: thanks. Did you figure out why the web hook was not working and is it working now?

**Comment by bgoli** [comment]
It turned out that a single value (the license id string) in the CFF was in an incorrect format and that trashed the whole thing. I will update the CFF and readme files and merge it.
