### ISSUE TITLE
Zenodo release for 1.0.2

### ISSUE THREAD

**Issue by jmrohwer** [PySCeS/pysces#78]
I have merged #77 and released [1.0.2](https://github.com/PySCeS/pysces/releases/tag/1.0.2), wheels are on PyPI and the Anaconda packages are uploaded as well.

@bgoli can you update the Zenodo release for 1.0.2 please, `CITATION.cff` will most probably have to be updated as well.

**Comment by jmrohwer** [comment]
`CITATION.cff` already updated. I have changed the DOI to the generic one that references all versions and always defaults to the latest version on Zenodo.

**Comment by bgoli** [comment]
The release didn't trigger an update to Zenodo. Something to look into next time.

**Comment by jmrohwer** [comment]
I tried re-delivery of the web hook. But no change. At the moment I don't have access to the PySCeS Zenodo site, getting the message "This repository is managed by another user of your Github organization". 
So I can't really debug this.

**Comment by bgoli** [comment]
There may have been some change on the Zenodo side, I see they offer an option to initiate a release from Zenodo so we can try that next time. I could also create a manual update to the latest version but I'll try redeliver the webhook first.

**Comment by jmrohwer** [comment]
This is still not working after yesterday's 1.0.3 release. I did update `.zenodo.json` in the source before making the release. Looking at the webhooks, it appears the hook was delivered 3 times in quick succession following the release, once each for:
- release.created
- release.released
- release.published

The first of these was delivered successfully (accepted) but the others were rejected, because the release ID already exists (not unique) which makes sense. However, the zenodo record is not updated. I can't debut this as pointed out [in this comment](https://github.com/PySCeS/pysces/issues/78#issuecomment-1134794505), @bgoli could you look into this?

**Comment by bgoli** [comment]
It appears Zenodo didn't like the isSupplementTo relation:
{
    "errors": "{'metadata': {'related_identifiers': {1: {'relation': [u'Not a valid choice.']}}}}"
}

I've deleted the relation out of the zenodo.json file but unfortunately with Zenodo you only get one chance per release so I we can't rerun the action without creating a new release.

**Comment by jmrohwer** [comment]
1. Is there a way to test that this will now work?
2. If it does indeed work, it is no problem just to make another minor point release (1.0.4) - the pypi wheels and anaconda packages are generated automatically.

The last Zenodo release (1.0.1) is really quite outdated by now. Specifically 1.0.2 had a number of bug fixes which affect part of the core functionality.

**Comment by bgoli** [comment]
Not sure, but one option would be to reduce the information to just basic
stuff in the cff file, and then fill the zenodo metadata afterwards.

I don't think that many people install stuff from the archive but it would
be good to have working.

**Comment by jmrohwer** [comment]
I see it still has not pulled through for the 1.1.0 release. @bgoli can you look at the logs again? I did update `.zenodo.json` as well as `CITATION.cff` before making the release.

**Comment by bgoli** [comment]
Zenodo is giving this error, so I've taken out that section in .zenodo.json ... we can test it with a point release sometime.

{
    "errors": "{'metadata': {'related_identifiers': {0: {'relation': [u'Not a valid choice.']}}}}"
}

**Comment by bgoli** [comment]
There was an extra comma in the json file which caused zenodo to fail again. It's easier to just update Zenodo by hand, whch I have now done for 1.1.1 https://doi.org/10.5281/zenodo.8187854
