### ISSUE TITLE
requirements.txt contains a wrong item 'nose'

### ISSUE THREAD

**Issue by yurivict** [PySCeS/pysces#82]
nose is a Python-2 package. In Python-3.x nose2 should be used. Python-2 is EOLed.

Also: install requirements shouldn't have nose or nose2 because nose is only used for testing.
There's no need to install tests or to make test framework required during runtime.

**Comment by jmrohwer** [comment]
Fixed in https://github.com/PySCeS/pysces/commit/3f6017d3b7ad513f5b82659f91bed80c2f698dfe
