### ISSUE TITLE
Numpy method MachAr is deprecated since version 1.22

### ISSUE THREAD

**Issue by olledejong** [PySCeS/pysces#88]
Exception is thrown when trying to import pysces. 

Can be worked around by downgrading numpy to a version < 1.22 for now.

<img width="1190" alt="Screenshot 2023-01-17 at 12 55 41" src="https://user-images.githubusercontent.com/63706210/212892762-82484739-69af-4978-a846-2dce8412e4fc.png">

**Comment by jmrohwer** [comment]
Thanks for this report! 
Fixed in 514729ccaa59978157211f1b4965b5a4595a14ef and will be incorporated in the next PySCeS release.
