### ISSUE TITLE
argument 'type' in PyscesPlot2.py function 'export'

### ISSUE THREAD

**Issue by olledejong** [PySCeS/pysces#89]
Argument 'type' seems to no longer exist, I guess it should be changed to 'outtype' instead?

PycesModel.py
<img width="661" alt="Screenshot 2023-01-17 at 15 58 32" src="https://user-images.githubusercontent.com/63706210/212932457-45621835-18d6-43c1-92d1-0b1cebbb4855.png">

PyscesPlot2.py
<img width="544" alt="Screenshot 2023-01-17 at 15 58 52" src="https://user-images.githubusercontent.com/63706210/212932531-f3e5d1bf-cb2c-4572-9fe3-f2469329a413.png">

There are four occurences of this.

**Comment by jmrohwer** [comment]
Thanks for bug report, fixed in 0a4cd8e23604c348882e0b0964fc56a3dd4633d5
