### ISSUE TITLE
Unify configuration across platforms

### ISSUE THREAD

**Issue by jmrohwer** [PySCeS/pysces#92]
I've been looking at adding a configuration option for pandas, as per the discussion in #91.

The configuration system is currently kludgy, being different for Windows and POSIX. This is mostly legacy. I am suggesting unifying and consolidating this:
- `os.path.expanduser('~')` works on all platforms and on Windows evaluates to the same path as `os.getenv('USERPROFILE')`, which is used currenty
- the install location can be obtained with `sysconfig.get_path('platlib')` which works on all platforms.

@bgoli any objections to this or am I missing something? We would then not need separate configuration code for win32.

**Comment by bgoli** [comment]
Pre windows 9 or 10 os.path.expanduser('~') did not work as expected on Windows and was even worse if MinGW or similar was installed and I had to hack something else. Both work as expected on Win11 so I would say go for it.

**Comment by jmrohwer** [comment]
Implemented in #91
