### ISSUE TITLE
Link listed in GitHub repo goes to SourceForge – should be updated to point to GitHub Pages

### ISSUE THREAD

**Issue by mhucka** [PySCeS/pysces#95]
The link for this repository, under the About section, still points to SourceForge:

<img width="300" alt="image" src="https://github.com/PySCeS/pysces/assets/1450019/3ae3f433-61a6-4ef6-ae14-6f9b736da8d8">

Probably best to set it to point to the GitHub Pages location.

**Comment by bgoli** [comment]
Many thanks Mike, I will update it as suggested.
